from __future__ import annotations

"""Leakage-safe encoding and preprocessing utilities for Notebook 05/06.

This module defines preprocessing objects only. It does not fit encoders,
imputers, scalers, or target encoders at feature-engineering time. Fitting must
happen inside the model-training pipeline using the training split only.
"""

import json
from pathlib import Path
from typing import Any

import pandas as pd

DEFAULT_ORDINAL_CATEGORIES: dict[str, list[str]] = {
    "tier_of_employment": ["Unknown", "A", "B", "C", "D", "E", "F"],
    "work_experience": ["Unknown", "<1", "1-2", "2-3", "3-5", "5-10", "10+"],
    "income_band": ["Missing", "<=50K", "50K-75K", "75K-100K", "100K-150K", ">150K"],
    "loan_amount_band": ["Missing", "<=10K", "10K-25K", "25K-50K", "50K-100K", ">100K"],
    "interest_rate_band": ["Missing", "<=8%", "8%-12%", "12%-16%", "16%-20%", ">20%"],
    "tenure_band": ["Missing", "<=1Y", "1Y-3Y", "3Y-5Y", ">5Y"],
    "loan_to_income_band": ["Missing", "<=10%", "10%-25%", "25%-50%", "50%-100%", ">100%"],
}

REQUIRED_GROUP_KEYS = [
    "target",
    "id_columns",
    "split_column",
    "continuous_numeric_features",
    "binary_features",
    "nominal_categorical_features",
    "ordinal_categorical_features",
]


def load_preprocessing_column_groups(path: str | Path) -> dict[str, Any]:
    """Load the column-group JSON generated by Notebook 05."""
    path = Path(path)
    with path.open("r", encoding="utf-8") as f:
        groups = json.load(f)
    validate_column_group_schema(groups)
    return groups


def validate_column_group_schema(groups: dict[str, Any]) -> None:
    """Validate the minimal JSON schema expected by the modelling pipeline."""
    missing = [key for key in REQUIRED_GROUP_KEYS if key not in groups]
    if missing:
        raise KeyError(f"Missing preprocessing column-group keys: {missing}")

    list_keys = [key for key in REQUIRED_GROUP_KEYS if key not in {"target", "split_column"}]
    non_lists = [key for key in list_keys if not isinstance(groups.get(key), list)]
    if non_lists:
        raise TypeError(f"Expected list values for keys: {non_lists}")


def available_feature_groups(modeling_df: pd.DataFrame, groups: dict[str, Any]) -> dict[str, list[str]]:
    """Return only columns that exist in the provided modelling dataset."""
    validate_column_group_schema(groups)
    return {
        "continuous_numeric_features": [
            c for c in groups.get("continuous_numeric_features", []) if c in modeling_df.columns
        ],
        "binary_features": [c for c in groups.get("binary_features", []) if c in modeling_df.columns],
        "nominal_categorical_features": [
            c for c in groups.get("nominal_categorical_features", []) if c in modeling_df.columns
        ],
        "ordinal_categorical_features": [
            c for c in groups.get("ordinal_categorical_features", []) if c in modeling_df.columns
        ],
    }


def build_ordinal_categories(
    ordinal_features: list[str],
    ordinal_mapping: dict[str, list[str]] | None = None,
) -> list[list[str]]:
    """Build category order list aligned with ordinal_features."""
    mapping = ordinal_mapping or DEFAULT_ORDINAL_CATEGORIES
    return [mapping.get(feature, ["Unknown"]) for feature in ordinal_features]


def build_preprocessor(
    modeling_df: pd.DataFrame,
    groups: dict[str, Any],
    *,
    scale_numeric: bool = False,
    ordinal_mapping: dict[str, list[str]] | None = None,
):
    """Build a sklearn ColumnTransformer without fitting it.

    Parameters
    ----------
    modeling_df:
        The unencoded modelling dataset created by Notebook 05.
    groups:
        Column-group JSON created by Notebook 05.
    scale_numeric:
        Set True for linear models. Tree-based models do not require scaling.
    ordinal_mapping:
        Optional custom ordinal mapping. Defaults to project mapping.

    Returns
    -------
    sklearn.compose.ColumnTransformer
        Unfitted preprocessing transformer.
    """
    try:
        from sklearn.compose import ColumnTransformer
        from sklearn.impute import SimpleImputer
        from sklearn.pipeline import Pipeline
        from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, StandardScaler
    except Exception as exc:  # pragma: no cover
        raise ImportError("scikit-learn is required to build preprocessing pipelines.") from exc

    cols = available_feature_groups(modeling_df, groups)
    continuous = cols["continuous_numeric_features"]
    binary = cols["binary_features"]
    nominal = cols["nominal_categorical_features"]
    ordinal = cols["ordinal_categorical_features"]

    numeric_steps = [("imputer", SimpleImputer(strategy="median"))]
    if scale_numeric:
        numeric_steps.append(("scaler", StandardScaler()))

    binary_steps = [("imputer", SimpleImputer(strategy="most_frequent"))]

    nominal_steps = [
        ("imputer", SimpleImputer(strategy="constant", fill_value="Unknown")),
        ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False)),
    ]

    ordinal_steps = [
        ("imputer", SimpleImputer(strategy="constant", fill_value="Unknown")),
        (
            "ordinal",
            OrdinalEncoder(
                categories=build_ordinal_categories(ordinal, ordinal_mapping),
                handle_unknown="use_encoded_value",
                unknown_value=-1,
            ),
        ),
    ]

    transformers = []
    if continuous:
        transformers.append(("continuous_numeric", Pipeline(numeric_steps), continuous))
    if binary:
        transformers.append(("binary", Pipeline(binary_steps), binary))
    if nominal:
        transformers.append(("nominal", Pipeline(nominal_steps), nominal))
    if ordinal:
        transformers.append(("ordinal", Pipeline(ordinal_steps), ordinal))

    if not transformers:
        raise ValueError("No available features were found for preprocessing.")

    return ColumnTransformer(transformers=transformers, remainder="drop", verbose_feature_names_out=True)


def get_preprocessor_feature_names(preprocessor, fallback_features: list[str] | None = None) -> list[str]:
    """Return transformed feature names from a fitted preprocessor when available."""
    try:
        return list(preprocessor.get_feature_names_out())
    except Exception:
        return fallback_features or []


def make_encoding_plan_table(groups: dict[str, Any]) -> pd.DataFrame:
    """Create a human-readable preprocessing plan from column groups."""
    validate_column_group_schema(groups)
    rows = [
        {
            "feature_group": "continuous_numeric_features",
            "feature_count": len(groups.get("continuous_numeric_features", [])),
            "features": ", ".join(groups.get("continuous_numeric_features", [])),
            "preprocessing": "SimpleImputer(strategy='median'); StandardScaler only for linear models",
            "fit_policy": "fit_on_training_split_only",
        },
        {
            "feature_group": "binary_features",
            "feature_count": len(groups.get("binary_features", [])),
            "features": ", ".join(groups.get("binary_features", [])),
            "preprocessing": "SimpleImputer(strategy='most_frequent'); keep 0/1",
            "fit_policy": "fit_on_training_split_only",
        },
        {
            "feature_group": "nominal_categorical_features",
            "feature_count": len(groups.get("nominal_categorical_features", [])),
            "features": ", ".join(groups.get("nominal_categorical_features", [])),
            "preprocessing": "SimpleImputer(fill_value='Unknown') + OneHotEncoder(handle_unknown='ignore')",
            "fit_policy": "fit_on_training_split_only",
        },
        {
            "feature_group": "ordinal_categorical_features",
            "feature_count": len(groups.get("ordinal_categorical_features", [])),
            "features": ", ".join(groups.get("ordinal_categorical_features", [])),
            "preprocessing": "SimpleImputer(fill_value='Unknown') + OrdinalEncoder with documented order",
            "fit_policy": "fit_on_training_split_only",
        },
    ]
    return pd.DataFrame(rows)
